### ISSUE TITLE
Unable to make comment/vote operation

### ISSUE THREAD

**Issue by ismelykh** [marvin-we/steem-java-api-wrapper#59] opened 2017-08-08 14:00 UTC
Hi, 

I'm trying to perfrom some posting operations but it always fails with 'missing required posting authority' server's responce.

```
...
            List<ImmutabePair<PrivateKeyType, String>> privateKeys = new ArrayList<>();
            privateKeys.add(new ImmutablePair<>(PrivateKeyType.POSTING, "5K~~~~~~~~~~~~~"));
            myConfig.getPrivateKeyStorage().addAccount(new AccountName("test"), privateKeys);
...
            CommentOperation commentOperation = new CommentOperation();
            commentOperation.setAuthor(new AccountName("test"));
            commentOperation.setBody("Test SteemJ");
            commentOperation.setJsonMetadata("{}");
            commentOperation.setParentAuthor(new AccountName("test"));
            commentOperation.setParentPermlink("TEST");
            commentOperation.setPermlink("re-steem-java-api-v0-2-0-has-been-released-update-6");
            commentOperation.setTitle("-TEST");

            ArrayList<Operation> operations = new ArrayList<>();
            Transaction transaction = new Transaction();
            
            operations.add(commentOperation);
            transaction.setOperations(operations);
            try {
                transaction.sign();
            } catch (SteemInvalidTransactionException e) {
                LOGGER.error("A propblem occured while signing your Transaction.", e);
            }
            steemApiWrapper.broadcastTransaction(transaction);
```
Any ideas?

Version used: 0.3.2 release.

Thanks in advance.

**Comment by marvin-we** [comment] 2017-08-08 15:19
Hay @ismelykh ,

Thank you for reporting this issue. Before investigating on this, I would like to make sure that 'test'  is your username on steemit on that the provided posting key belongs to that user :)

Can you confirm this? 😊

**Comment by ismelykh** [comment] 2017-08-08 15:32
Hi @marvin-we 

This is the user on my local docker image I made by my own based on steamit image.

**Comment by marvin-we** [comment] 2017-08-08 16:57
I see 😊 okay, so even when you are using your own node, you need a valid steem account. The easiest way to get this account is to register on steemit.com for all actions (using SteemJ, becoming a Witness, ...)

Please let me know if its working when you use your steemit username and the its posting key (can be found in the wallet tab at steemJ

**Comment by ismelykh** [comment] 2017-08-08 17:40
Confirming it works with steamit, at least for voting.

I'm triying to create my isolated node, is it not possible or I just didn't configure something properly?
I've created test user using webui on my own server and used the keys from wallet/permissions page.

Thanks for your support.

**Comment by marvin-we** [comment] 2017-08-09 18:17
Hay @ismelykh ,

thank you once again for your fast reply. I would suggest to create an issue at the Steemit/Steem or Steemit/Condenser GitHub Repo and ask about the setup of an isolated node - I think there are better experts for those topics than I am :D 

In general you can use SteemJ with every Steem Node running on version >0.19.0 - So when you've setup your own node and created the account correctly, it should work too. 

I'll close this issue because you've mentioned that SteemJ is working when you use your Steemit-Account, so I assume that SteemJ itself is working and that your initial problem is caused by a wrong Node configuration.

Thank you once again and best regards!

**Closed by marvin-we** 2017-08-09 18:17 UTC
Labels: question
