### ISSUE TITLE
Not able to post comment

### ISSUE THREAD

**Issue by saggammahesh** [marvin-we/steem-java-api-wrapper#24] opened 2017-06-15 18:38 UTC
Hi,
I am not able to post comment to one post.. I am getting error "Missing Posting Authority <username>". I've configured correct posting key and not sure what is the issue.

below is the code i am using.
`CommentOperation commentOperation = new CommentOperation();
	            commentOperation.setAuthor(new AccountName("<comment_posting_username>"));
	            commentOperation.setBody("text");
	            commentOperation.setPermlink("re-<permalink_of_post>");
	            
	            commentOperation.setJsonMetadata("{}");
	            commentOperation.setParentAuthor(new AccountName("<username>"));
	            commentOperation.setParentPermlink("<post_permalink>");
	            commentOperation.setTitle("-");
	            
	            List<Operation> operations = new ArrayList<Operation>();
	            operations.add(commentOperation);
	            GlobalProperties globalProperties = steemApiWrapper.getDynamicGlobalProperties();
	            int refBlockNum = (globalProperties.getHeadBlockNumber() & 0xFFFF);

	            Transaction transaction = new Transaction();
	            transaction.setRefBlockNum(refBlockNum);
	            transaction.setRefBlockPrefix(globalProperties.getHeadBlockId());
	            transaction.setOperations(operations);
	            try {
	                transaction.sign();
	            } catch (SteemInvalidTransactionException e) {
	                LOGGER.error("A propblem occured while signing your Transaction.", e);
	            }
	            steemApiWrapper.broadcastTransaction(transaction);
	            LOGGER.info("The HEX representation of this transaction it {}.", steemApiWrapper.getTransactionHex(transaction));`

**Comment by marvin-we** [comment] 2017-06-15 19:12
Hay saggammahesh,

thanks for the report. 

Actually I can't reproduce the issue. The following code:

```JAVA
            SteemJConfig myConfig = SteemJConfig.getInstance();
            myConfig.setPrivateKey(PrivateKeyType.POSTING, "SUPERDUPERPRIVATEKEY");

            CommentOperation commentOperation = new CommentOperation();
            commentOperation.setAuthor(new AccountName("dez1337"));
            commentOperation.setBody("Thank you for the support =).");
            commentOperation.setPermlink("posted-with-steemj");
            commentOperation.setJsonMetadata("{}");
            commentOperation.setParentAuthor(new AccountName("alphacore"));
            commentOperation.setParentPermlink("re-dez1337-steemj-v0-2-6-has-been-released-update-11-2017615t919269z");
            commentOperation.setTitle("-");

            operations.add(commentOperation);
            
            GlobalProperties globalProperties = steemApiWrapper.getDynamicGlobalProperties();
            int refBlockNum = (globalProperties.getHeadBlockNumber() & 0xFFFF);

            Transaction transaction = new Transaction();
            transaction.setRefBlockNum(refBlockNum);
            transaction.setRefBlockPrefix(globalProperties.getHeadBlockId());
            transaction.setOperations(operations);

            try {
                transaction.sign();
            } catch (SteemInvalidTransactionException e) {
                LOGGER.error("A propblem occured while signing your Transaction.", e);
            }
            steemApiWrapper.broadcastTransaction(transaction);
```

Generated [this comment](https://steemit.com/steem-dev/@dez1337/steemj-v0-2-6-has-been-released-update-11#@dez1337/posted-with-steemj) on Steemit.

Sadly, the error response from a SteemNode is not that accurate so if the snippet above does not help it becomes difficult. Could you please provide the following information:
* Which node do you use?
* What timezone is configured?
* Are there special characters in your text?

Thanks and best regards!

**Comment by saggammahesh** [comment] 2017-06-16 03:19
Hi Marvin-We,
I think problem with comment body text.
I able to reply with simple comment boy text like "welcome".

But failing if comment text is bit longer. for instance it's failing for below text.
"Can you find who is engineer and doctor based on below statements. sounds like really great work you're doing with this.Can you find who is engineer and doctor based on below statements."

**Comment by marvin-we** [comment] 2017-06-16 18:43
Thanks for providing that test String - I can now reproduce the issue and will try to provide a fix asap :)

**Comment by marvin-we** [comment] 2017-06-16 20:31
Should be fixed with the latest commit. Could you try to pull the latest master branch and retest it?

Thanks and best regards!

**Comment by saggammahesh** [comment] 2017-06-17 04:37
Hi Marvin,
I see your commits for the issue,  But i can not test it because of compilation issues in the class SteemAPIWrapper.
Issue:  eu.bittrade.libs.steem.api.wrapper.models.Discussion  can not be resolved to type.

**Comment by saggammahesh** [comment] 2017-07-13 10:30
Still this issue is there in the version 0.3.0

**Comment by marvin-we** [comment] 2017-07-21 16:26
Hay @saggammahesh ,

I am about to release version 0.3.1 in this moment :) This release solves some problems of the comment operation reported by @sesangsokuro . 

Could you please have a look at [this test case](https://github.com/marvin-we/steem-java-api-wrapper/blob/master/src/test/java/eu/bittrade/libs/steemj/base/models/operations/CommentOperationIT.java) and try to adapt it for your sample? As reported by @sesangsokuro SteemJ 0.3.0 only supported ASCII so it could also be that you face some encoding problems. Please try to set the encoding to UTF-8 like its shown by the linked test and let me know if this solves your problem.

Thank you and best regards!

**Closed** 2017-08-20 19:13 UTC
Labels: bug
