### ISSUE TITLE
Limit the number of connection retries in CommunicationHandler

### ISSUE THREAD

**Issue by edTheGuy00** [marvin-we/steem-java-api-wrapper#143] opened 2017-10-29 01:19 UTC
I'm stuck in an endless loop of "Could not connect to the node - Trying to reconnect.", I noticed that ConnectionHandler does't limit the numberOfConnectionTries. 

As far as my error, it seems I'm unable to connect to the server with no error message

**Comment by marvin-we** [comment] 2017-10-31 08:58
Hay @edTheGuy00 and sorry for the late reply. 

> As far as my error, it seems I'm unable to connect to the server with no error message

The code looks like this:

```JAVA
LOGGER.info("Could not connect to the node - Trying to reconnect.");
LOGGER.debug("Reason:", e);
```

So when you raise the log level in your logging configuration to "DEBUG" you should be able to see the root cause =) Could you paste the stacktrace here?

> I noticed that ConnectionHandler does't limit the numberOfConnectionTries.

True, because my thought was that you do never want SteemJ to stop working because of a small connection outage - That's why it is always trying to reconnect. If you have some good arguments to change it please let me know and I'll implement a limit :)

**Comment by edTheGuy00** [comment] 2017-10-31 23:09
`10-31 17:31:29.963 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Connecting to wss://steemd.steemit.com.
10-31 17:31:29.972 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: The connection has been closed due to a failure.
10-31 17:31:29.974 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Could not connect to the node - Trying to reconnect.
10-31 17:31:29.974 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Connecting to wss://seed.bitcoiner.me.
10-31 17:31:29.983 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: The connection has been closed due to a failure.
10-31 17:31:29.984 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Could not connect to the node - Trying to reconnect.
10-31 17:31:29.985 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Connecting to wss://steemd.minnowsupportproject.org.
10-31 17:31:29.994 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: The connection has been closed due to a failure.
10-31 17:31:29.995 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Could not connect to the node - Trying to reconnect.
10-31 17:31:29.995 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Connecting to wss://steemd.steemit.com.
10-31 17:31:30.005 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: The connection has been closed due to a failure.
10-31 17:31:30.007 16367-16367/com.taskail.mixion I/eblsc.CommunicationHand: Could not connect to the node - Trying to reconnect.`

My guess is that the Tyrus client manager does not work well on Android, or I may be doing something wrong. Running on a background thread i still get an ANR that endlessly loops through this error. I'm not entirely sure what the issue is.

**Comment by marvin-we** [comment] 2017-11-01 08:54
Thank you for providing the logs =) 

> My guess is that the Tyrus client manager does not work well on Android, or I may be doing something wrong. 

As I said in another thread I sadly do not have an android test environment - So I can only guess what is going on there... Maybe @ray66rus has another quick hint or can tell you what he did.

Beside that you could "upgrade" to [0.4.2pre1](https://github.com/marvin-we/steem-java-api-wrapper/releases/tag/v0.4.2pr1) which has a HTTP Client on board. It is for sure not production ready but it should allow you to test if you face the same issues without using tyrus. 

Could you please provide me some updates if that version is working or not? =)

**Comment by marvin-we** [comment] 2017-11-04 19:52
The problem has also been reproduced on non Android devices - I'll try to check to investigate what the root cause is.

**Comment by marvin-we** [comment] 2017-11-14 20:09
Hay @edTheGuy00 - I've deployed a pre-release (0.4.3pre1) which has been tested on Android by another user. 

I'll close this issue for now - If you test newer versions and still face the problem please comment here and I'll reopen the issue again.

Thanks once again and best regards!

**Closed by marvin-we** 2017-11-14 20:09 UTC
Labels: Investigation needed
